version: '3'

volumes:
  postgres_volume:
    driver: local

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres